export type Food = {
  addedSugars: number;
  alcohol: number;
  calories: number;
  darkGreenVegetables: number;
  dryBeansPeas: number;
  factor: number;
  fruits: number;
  grains: number;
  id: string;
  increment: number;
  meats: number;
  milk: number;
  multiplier: number;
  name: string;
  oils: number;
  orangeVegetables: number;
  otherVegetables: number;
  portion: number;
  portionAmount: number;
  portionDisplayName: string;
  saturatedFats: number;
  solidFats: number;
  soy: number;
  starchyVegetables: number;
  vegetables: number;
  wholeGrains: number;
};
